// Render OpenAPI components + JSON example files.

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { stringify as yaml } from 'yaml'
import { scanSchemas } from './scanner.js'
import { zodToOpenAPI } from './zod-to-schema.js'
import { extractExample } from './examples.js'
import type { BuildContext, Plugin } from './types.js'
import type { ZodTypeAny } from 'zod'

export interface BuildOptions {
  src: string
  out: string
  plugins?: Plugin[]
  /** Output format for schema + index files. Examples are always JSON. */
  format?: 'yaml' | 'json'
  /** OpenAPI version string on the index file. Default '3.2.0'. */
  openapiVersion?: '3.1.0' | '3.2.0'
}

export async function build(opts: BuildOptions): Promise<BuildContext> {
  const format = opts.format ?? 'yaml'
  const ext = format === 'json' ? 'json' : 'yaml'

  const schemas = await scanSchemas(opts.src)

  // Build cross-schema $ref registry: each scanned schema → its export name.
  const registry = new Map<ZodTypeAny, string>()
  for (const info of schemas) {
    registry.set(info.zod, info.name)
  }

  const components: Record<string, unknown> = {}
  const examples: Record<string, unknown> = {}

  for (const info of schemas) {
    let schema = zodToOpenAPI(info, registry)
    for (const p of opts.plugins ?? []) {
      if (p.transformSchema) schema = await p.transformSchema(schema, info)
    }
    components[info.name] = schema
    const ex = extractExample(info.zod)
    if (ex !== undefined) examples[info.name] = ex
  }

  const outputs = new Map<string, string>()

  // components/schemas/<Name>.<ext> — one file per schema for clean diffs
  for (const [name, schema] of Object.entries(components)) {
    const content = format === 'json' ? JSON.stringify({ [name]: schema }, null, 2) + '\n' : yaml({ [name]: schema })
    outputs.set(path.join('components', 'schemas', `${name}.${ext}`), content)
  }

  // examples/<name>.json (always JSON regardless of --format)
  for (const [name, ex] of Object.entries(examples)) {
    outputs.set(path.join('examples', `${kebab(name)}.json`), JSON.stringify(ex, null, 2) + '\n')
  }

  // index.<ext> at the root
  const indexPayload = {
    openapi: opts.openapiVersion ?? '3.2.0',
    info: { title: 'Generated by zod-contract', version: '0.1.0' },
    components: {
      schemas: Object.fromEntries(
        Object.keys(components).map((n) => [n, { $ref: `components/schemas/${n}.${ext}#/${n}` }]),
      ),
    },
  }
  outputs.set(
    `index.${ext}`,
    format === 'json' ? JSON.stringify(indexPayload, null, 2) + '\n' : yaml(indexPayload),
  )

  let ctx: BuildContext = { schemas, outputs, format }
  for (const p of opts.plugins ?? []) {
    if (p.finalize) ctx = await p.finalize(ctx)
  }

  // write all outputs
  await fs.mkdir(opts.out, { recursive: true })
  for (const [rel, content] of ctx.outputs) {
    const full = path.join(opts.out, rel)
    await fs.mkdir(path.dirname(full), { recursive: true })
    await fs.writeFile(full, content)
  }

  return ctx
}

function kebab(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
}
